// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(CsPharmaSprintFinalContext))]
    partial class CsPharmaSprintFinalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.TdcCatEstadosDevolucionPedido", b =>
                {
                    b.Property<string>("CodEstadoDevolucion")
                        .HasColumnType("text")
                        .HasColumnName("Cod_estado_devolucion");

                    b.Property<string>("DesEstadoDevolucion")
                        .HasColumnType("text")
                        .HasColumnName("Des_estado_devolucion");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MdDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<string>("MdUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Md_uuid");

                    b.HasKey("CodEstadoDevolucion");

                    b.ToTable("tdc_cat_estados_devolucion_pedido", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Models.TdcCatEstadosEnvioPedido", b =>
                {
                    b.Property<string>("CodEstadoEnvio")
                        .HasColumnType("text")
                        .HasColumnName("Cod_estado_envio");

                    b.Property<string>("DesEstadoEnvio")
                        .HasColumnType("text")
                        .HasColumnName("Des_estado_envio");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MdDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<string>("MdUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Md_uuid");

                    b.HasKey("CodEstadoEnvio");

                    b.ToTable("Tdc_cat_estados_envio_pedido", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Models.TdcCatEstadosPagoPedido", b =>
                {
                    b.Property<string>("CodEstadoPago")
                        .HasColumnType("text")
                        .HasColumnName("Cod_estado_pago");

                    b.Property<string>("DesEstadoPago")
                        .HasColumnType("text")
                        .HasColumnName("Des_estado_pago");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MdDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<string>("MdUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Md_uuid");

                    b.HasKey("CodEstadoPago");

                    b.ToTable("Tdc_cat_estados_pago_pedido", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Models.TdcCatLineasDistribucion", b =>
                {
                    b.Property<string>("CodLinea")
                        .HasColumnType("text")
                        .HasColumnName("Cod_linea");

                    b.Property<string>("CodBarrio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cod_barrio");

                    b.Property<string>("CodMunicipio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cod_municipio");

                    b.Property<string>("CodProvincia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cod_provincia");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("MdDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<string>("MdUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Md_uuid");

                    b.HasKey("CodLinea");

                    b.ToTable("Tdc_cat_lineas_distribucion", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Models.TdcTchEstadoPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodEstadoDevolucion")
                        .HasColumnType("text")
                        .HasColumnName("Cod_estado_devolucion");

                    b.Property<string>("CodEstadoEnvio")
                        .HasColumnType("text")
                        .HasColumnName("Cod_estado_envio");

                    b.Property<string>("CodEstadoPago")
                        .HasColumnType("text")
                        .HasColumnName("Cod_estado_pago");

                    b.Property<string>("CodLinea")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cod_linea");

                    b.Property<string>("CodPedido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cod_pedido");

                    b.Property<DateTime>("MdDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("Md_date");

                    b.Property<string>("MdUuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Md_uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodEstadoDevolucion" }, "IX_Tdc_tch_estado_pedidos_Cod_estado_devolucion");

                    b.HasIndex(new[] { "CodEstadoEnvio" }, "IX_Tdc_tch_estado_pedidos_Cod_estado_envio");

                    b.HasIndex(new[] { "CodEstadoPago" }, "IX_Tdc_tch_estado_pedidos_Cod_estado_pago");

                    b.HasIndex(new[] { "CodLinea" }, "IX_Tdc_tch_estado_pedidos_Cod_linea");

                    b.ToTable("Tdc_tch_estado_pedidos", "dwh_torrecontrol");
                });

            modelBuilder.Entity("DAL.Models.TdcTchEstadoPedido", b =>
                {
                    b.HasOne("DAL.Models.TdcCatEstadosDevolucionPedido", "CodEstadoDevolucionNavigation")
                        .WithMany("TdcTchEstadoPedidos")
                        .HasForeignKey("CodEstadoDevolucion")
                        .HasConstraintName("FK_Tdc_tch_estado_pedidos_tdc_cat_estados_devolucion_pedido_Co~");

                    b.HasOne("DAL.Models.TdcCatEstadosEnvioPedido", "CodEstadoEnvioNavigation")
                        .WithMany("TdcTchEstadoPedidos")
                        .HasForeignKey("CodEstadoEnvio")
                        .HasConstraintName("FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_envio_pedido_Cod_est~");

                    b.HasOne("DAL.Models.TdcCatEstadosPagoPedido", "CodEstadoPagoNavigation")
                        .WithMany("TdcTchEstadoPedidos")
                        .HasForeignKey("CodEstadoPago")
                        .HasConstraintName("FK_Tdc_tch_estado_pedidos_Tdc_cat_estados_pago_pedido_Cod_esta~");

                    b.HasOne("DAL.Models.TdcCatLineasDistribucion", "CodLineaNavigation")
                        .WithMany("TdcTchEstadoPedidos")
                        .HasForeignKey("CodLinea")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodEstadoDevolucionNavigation");

                    b.Navigation("CodEstadoEnvioNavigation");

                    b.Navigation("CodEstadoPagoNavigation");

                    b.Navigation("CodLineaNavigation");
                });

            modelBuilder.Entity("DAL.Models.TdcCatEstadosDevolucionPedido", b =>
                {
                    b.Navigation("TdcTchEstadoPedidos");
                });

            modelBuilder.Entity("DAL.Models.TdcCatEstadosEnvioPedido", b =>
                {
                    b.Navigation("TdcTchEstadoPedidos");
                });

            modelBuilder.Entity("DAL.Models.TdcCatEstadosPagoPedido", b =>
                {
                    b.Navigation("TdcTchEstadoPedidos");
                });

            modelBuilder.Entity("DAL.Models.TdcCatLineasDistribucion", b =>
                {
                    b.Navigation("TdcTchEstadoPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
